//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the geo_local_planner package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __geo_local_planner__GEOLOCALPLANNERRECONFIGURECONFIG_H__
#define __geo_local_planner__GEOLOCALPLANNERRECONFIGURECONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace geo_local_planner
{
  class GeoLocalPlannerReconfigureConfigStatics;

  class GeoLocalPlannerReconfigureConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(GeoLocalPlannerReconfigureConfig &config, const GeoLocalPlannerReconfigureConfig &max, const GeoLocalPlannerReconfigureConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const GeoLocalPlannerReconfigureConfig &config1, const GeoLocalPlannerReconfigureConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, GeoLocalPlannerReconfigureConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const GeoLocalPlannerReconfigureConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, GeoLocalPlannerReconfigureConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const GeoLocalPlannerReconfigureConfig &config) const = 0;
      virtual void getValue(const GeoLocalPlannerReconfigureConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T GeoLocalPlannerReconfigureConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T GeoLocalPlannerReconfigureConfig::* field;

      virtual void clamp(GeoLocalPlannerReconfigureConfig &config, const GeoLocalPlannerReconfigureConfig &max, const GeoLocalPlannerReconfigureConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const GeoLocalPlannerReconfigureConfig &config1, const GeoLocalPlannerReconfigureConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, GeoLocalPlannerReconfigureConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const GeoLocalPlannerReconfigureConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, GeoLocalPlannerReconfigureConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const GeoLocalPlannerReconfigureConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const GeoLocalPlannerReconfigureConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, GeoLocalPlannerReconfigureConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, GeoLocalPlannerReconfigureConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<GeoLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(GeoLocalPlannerReconfigureConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class ROBOT
{
  public:
    ROBOT()
    {
      state = true;
      name = "Robot";
    }

    void setParams(GeoLocalPlannerReconfigureConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("max_vel_x"==(*_i)->name){max_vel_x = boost::any_cast<double>(val);}
        if("max_vel_x_backwards"==(*_i)->name){max_vel_x_backwards = boost::any_cast<double>(val);}
        if("max_vel_theta"==(*_i)->name){max_vel_theta = boost::any_cast<double>(val);}
        if("acc_lim_x"==(*_i)->name){acc_lim_x = boost::any_cast<double>(val);}
        if("acc_lim_theta"==(*_i)->name){acc_lim_theta = boost::any_cast<double>(val);}
        if("min_turn_radius"==(*_i)->name){min_turn_radius = boost::any_cast<double>(val);}
        if("turn_around_priority"==(*_i)->name){turn_around_priority = boost::any_cast<bool>(val);}
        if("stop_dist"==(*_i)->name){stop_dist = boost::any_cast<double>(val);}
        if("dec_dist"==(*_i)->name){dec_dist = boost::any_cast<double>(val);}
      }
    }

    double max_vel_x;
double max_vel_x_backwards;
double max_vel_theta;
double acc_lim_x;
double acc_lim_theta;
double min_turn_radius;
bool turn_around_priority;
double stop_dist;
double dec_dist;

    bool state;
    std::string name;

    
}robot;

class GOALTOLERANCE
{
  public:
    GOALTOLERANCE()
    {
      state = true;
      name = "GoalTolerance";
    }

    void setParams(GeoLocalPlannerReconfigureConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("xy_goal_tolerance"==(*_i)->name){xy_goal_tolerance = boost::any_cast<double>(val);}
        if("yaw_goal_tolerance"==(*_i)->name){yaw_goal_tolerance = boost::any_cast<double>(val);}
      }
    }

    double xy_goal_tolerance;
double yaw_goal_tolerance;

    bool state;
    std::string name;

    
}goaltolerance;

class GEOPATH
{
  public:
    GEOPATH()
    {
      state = true;
      name = "geopath";
    }

    void setParams(GeoLocalPlannerReconfigureConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    
}geopath;

class TRAJECTORY
{
  public:
    TRAJECTORY()
    {
      state = true;
      name = "trajectory";
    }

    void setParams(GeoLocalPlannerReconfigureConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("max_local_plan_lookahead_dist"==(*_i)->name){max_local_plan_lookahead_dist = boost::any_cast<double>(val);}
        if("local_plan_viapoint_sep"==(*_i)->name){local_plan_viapoint_sep = boost::any_cast<double>(val);}
        if("local_plan_goal_sep"==(*_i)->name){local_plan_goal_sep = boost::any_cast<double>(val);}
        if("local_plan_prune_distance"==(*_i)->name){local_plan_prune_distance = boost::any_cast<double>(val);}
      }
    }

    double max_local_plan_lookahead_dist;
double local_plan_viapoint_sep;
double local_plan_goal_sep;
double local_plan_prune_distance;

    bool state;
    std::string name;

    
}trajectory;

class OPTIMIZATION
{
  public:
    OPTIMIZATION()
    {
      state = true;
      name = "Optimization";
    }

    void setParams(GeoLocalPlannerReconfigureConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("k_rho"==(*_i)->name){k_rho = boost::any_cast<double>(val);}
        if("k_alpha"==(*_i)->name){k_alpha = boost::any_cast<double>(val);}
        if("k_phi"==(*_i)->name){k_phi = boost::any_cast<double>(val);}
      }
    }

    double k_rho;
double k_alpha;
double k_phi;

    bool state;
    std::string name;

    
}optimization;

}groups;



//#line 25 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double max_vel_x;
//#line 29 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double max_vel_x_backwards;
//#line 33 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double max_vel_theta;
//#line 37 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double acc_lim_x;
//#line 41 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double acc_lim_theta;
//#line 45 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double min_turn_radius;
//#line 49 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      bool turn_around_priority;
//#line 53 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double stop_dist;
//#line 57 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double dec_dist;
//#line 65 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double xy_goal_tolerance;
//#line 69 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double yaw_goal_tolerance;
//#line 81 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double max_local_plan_lookahead_dist;
//#line 85 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double local_plan_viapoint_sep;
//#line 89 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double local_plan_goal_sep;
//#line 93 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double local_plan_prune_distance;
//#line 100 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double k_rho;
//#line 104 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double k_alpha;
//#line 108 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      double k_phi;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("GeoLocalPlannerReconfigureConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const GeoLocalPlannerReconfigureConfig &__max__ = __getMax__();
      const GeoLocalPlannerReconfigureConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const GeoLocalPlannerReconfigureConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const GeoLocalPlannerReconfigureConfig &__getDefault__();
    static const GeoLocalPlannerReconfigureConfig &__getMax__();
    static const GeoLocalPlannerReconfigureConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const GeoLocalPlannerReconfigureConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void GeoLocalPlannerReconfigureConfig::ParamDescription<std::string>::clamp(GeoLocalPlannerReconfigureConfig &config, const GeoLocalPlannerReconfigureConfig &max, const GeoLocalPlannerReconfigureConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class GeoLocalPlannerReconfigureConfigStatics
  {
    friend class GeoLocalPlannerReconfigureConfig;

    GeoLocalPlannerReconfigureConfigStatics()
    {
GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT, GeoLocalPlannerReconfigureConfig> Default("Default", "", 0, 0, true, &GeoLocalPlannerReconfigureConfig::groups);
GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT::ROBOT, GeoLocalPlannerReconfigureConfig::DEFAULT> Robot("Robot", "tab", 0, 1, true, &GeoLocalPlannerReconfigureConfig::DEFAULT::robot);
//#line 25 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.max_vel_x = 0.01;
//#line 25 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.max_vel_x = 100.0;
//#line 25 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.max_vel_x = 0.3;
//#line 25 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      Robot.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("max_vel_x", "double", 0, "Maximum velocity in the x direction of the robot", "", &GeoLocalPlannerReconfigureConfig::max_vel_x)));
//#line 25 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("max_vel_x", "double", 0, "Maximum velocity in the x direction of the robot", "", &GeoLocalPlannerReconfigureConfig::max_vel_x)));
//#line 29 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.max_vel_x_backwards = 0.01;
//#line 29 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.max_vel_x_backwards = 100.0;
//#line 29 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.max_vel_x_backwards = 0.2;
//#line 29 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      Robot.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("max_vel_x_backwards", "double", 0, "Maximum translational velocity of the robot for driving backwards", "", &GeoLocalPlannerReconfigureConfig::max_vel_x_backwards)));
//#line 29 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("max_vel_x_backwards", "double", 0, "Maximum translational velocity of the robot for driving backwards", "", &GeoLocalPlannerReconfigureConfig::max_vel_x_backwards)));
//#line 33 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.max_vel_theta = 0.01;
//#line 33 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.max_vel_theta = 100.0;
//#line 33 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.max_vel_theta = 0.5;
//#line 33 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      Robot.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("max_vel_theta", "double", 0, "Maximum angular velocity of the robot", "", &GeoLocalPlannerReconfigureConfig::max_vel_theta)));
//#line 33 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("max_vel_theta", "double", 0, "Maximum angular velocity of the robot", "", &GeoLocalPlannerReconfigureConfig::max_vel_theta)));
//#line 37 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.acc_lim_x = 0.01;
//#line 37 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.acc_lim_x = 100.0;
//#line 37 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.acc_lim_x = 0.5;
//#line 37 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      Robot.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("acc_lim_x", "double", 0, "Maximum translational acceleration of the robot", "", &GeoLocalPlannerReconfigureConfig::acc_lim_x)));
//#line 37 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("acc_lim_x", "double", 0, "Maximum translational acceleration of the robot", "", &GeoLocalPlannerReconfigureConfig::acc_lim_x)));
//#line 41 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.acc_lim_theta = 0.01;
//#line 41 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.acc_lim_theta = 100.0;
//#line 41 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.acc_lim_theta = 0.52;
//#line 41 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      Robot.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("acc_lim_theta", "double", 0, "Maximum angular acceleration of the robot", "", &GeoLocalPlannerReconfigureConfig::acc_lim_theta)));
//#line 41 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("acc_lim_theta", "double", 0, "Maximum angular acceleration of the robot", "", &GeoLocalPlannerReconfigureConfig::acc_lim_theta)));
//#line 45 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.min_turn_radius = 0.1;
//#line 45 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.min_turn_radius = 100.0;
//#line 45 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.min_turn_radius = 0.5;
//#line 45 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      Robot.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("min_turn_radius", "double", 0, "Minimum turning radius of the robot", "", &GeoLocalPlannerReconfigureConfig::min_turn_radius)));
//#line 45 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("min_turn_radius", "double", 0, "Minimum turning radius of the robot", "", &GeoLocalPlannerReconfigureConfig::min_turn_radius)));
//#line 49 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.turn_around_priority = 0;
//#line 49 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.turn_around_priority = 1;
//#line 49 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.turn_around_priority = 1;
//#line 49 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      Robot.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<bool>("turn_around_priority", "bool", 0, "If true, the robot preferentially adjusts the orientation to fit the direction of the path", "", &GeoLocalPlannerReconfigureConfig::turn_around_priority)));
//#line 49 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<bool>("turn_around_priority", "bool", 0, "If true, the robot preferentially adjusts the orientation to fit the direction of the path", "", &GeoLocalPlannerReconfigureConfig::turn_around_priority)));
//#line 53 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.stop_dist = 0.01;
//#line 53 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.stop_dist = 100.0;
//#line 53 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.stop_dist = 0.5;
//#line 53 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      Robot.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("stop_dist", "double", 0, "When the Euclidean distance between the nearest lethal point on planned path and the robot frame origin is less than this distance, the robot stops", "", &GeoLocalPlannerReconfigureConfig::stop_dist)));
//#line 53 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("stop_dist", "double", 0, "When the Euclidean distance between the nearest lethal point on planned path and the robot frame origin is less than this distance, the robot stops", "", &GeoLocalPlannerReconfigureConfig::stop_dist)));
//#line 57 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.dec_dist = 0.01;
//#line 57 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.dec_dist = 100.0;
//#line 57 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.dec_dist = 1.0;
//#line 57 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      Robot.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("dec_dist", "double", 0, "When the Euclidean distance between the nearest lethal point on planned path and the robot frame origin is less than this distance, the robot slows down", "", &GeoLocalPlannerReconfigureConfig::dec_dist)));
//#line 57 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("dec_dist", "double", 0, "When the Euclidean distance between the nearest lethal point on planned path and the robot frame origin is less than this distance, the robot slows down", "", &GeoLocalPlannerReconfigureConfig::dec_dist)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Robot.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(GeoLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT::ROBOT, GeoLocalPlannerReconfigureConfig::DEFAULT>(Robot)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT::ROBOT, GeoLocalPlannerReconfigureConfig::DEFAULT>(Robot)));
GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT::GOALTOLERANCE, GeoLocalPlannerReconfigureConfig::DEFAULT> GoalTolerance("GoalTolerance", "tab", 0, 2, true, &GeoLocalPlannerReconfigureConfig::DEFAULT::goaltolerance);
//#line 65 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.xy_goal_tolerance = 0.001;
//#line 65 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.xy_goal_tolerance = 10.0;
//#line 65 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.xy_goal_tolerance = 1.0;
//#line 65 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      GoalTolerance.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("xy_goal_tolerance", "double", 0, "Allowed final euclidean distance to the goal position", "", &GeoLocalPlannerReconfigureConfig::xy_goal_tolerance)));
//#line 65 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("xy_goal_tolerance", "double", 0, "Allowed final euclidean distance to the goal position", "", &GeoLocalPlannerReconfigureConfig::xy_goal_tolerance)));
//#line 69 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.yaw_goal_tolerance = 0.001;
//#line 69 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.yaw_goal_tolerance = 3.2;
//#line 69 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.yaw_goal_tolerance = 0.1;
//#line 69 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      GoalTolerance.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("yaw_goal_tolerance", "double", 0, "Allowed final orientation error to the goal orientation", "", &GeoLocalPlannerReconfigureConfig::yaw_goal_tolerance)));
//#line 69 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("yaw_goal_tolerance", "double", 0, "Allowed final orientation error to the goal orientation", "", &GeoLocalPlannerReconfigureConfig::yaw_goal_tolerance)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      GoalTolerance.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(GeoLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT::GOALTOLERANCE, GeoLocalPlannerReconfigureConfig::DEFAULT>(GoalTolerance)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT::GOALTOLERANCE, GeoLocalPlannerReconfigureConfig::DEFAULT>(GoalTolerance)));
GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT::GEOPATH, GeoLocalPlannerReconfigureConfig::DEFAULT> geopath("geopath", "tab", 0, 3, true, &GeoLocalPlannerReconfigureConfig::DEFAULT::geopath);
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      geopath.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(GeoLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT::GEOPATH, GeoLocalPlannerReconfigureConfig::DEFAULT>(geopath)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT::GEOPATH, GeoLocalPlannerReconfigureConfig::DEFAULT>(geopath)));
GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT::TRAJECTORY, GeoLocalPlannerReconfigureConfig::DEFAULT> trajectory("trajectory", "tab", 0, 4, true, &GeoLocalPlannerReconfigureConfig::DEFAULT::trajectory);
//#line 81 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.max_local_plan_lookahead_dist = 0.0;
//#line 81 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.max_local_plan_lookahead_dist = 50.0;
//#line 81 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.max_local_plan_lookahead_dist = 5.0;
//#line 81 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      trajectory.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("max_local_plan_lookahead_dist", "double", 0, "Specify maximum length (cumulative Euclidean distances) of the subset of the global plan taken into account for optimization [if 0 or negative: disabled; the length is also bounded by the local costmap size]", "", &GeoLocalPlannerReconfigureConfig::max_local_plan_lookahead_dist)));
//#line 81 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("max_local_plan_lookahead_dist", "double", 0, "Specify maximum length (cumulative Euclidean distances) of the subset of the global plan taken into account for optimization [if 0 or negative: disabled; the length is also bounded by the local costmap size]", "", &GeoLocalPlannerReconfigureConfig::max_local_plan_lookahead_dist)));
//#line 85 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.local_plan_viapoint_sep = -0.1;
//#line 85 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.local_plan_viapoint_sep = 10.0;
//#line 85 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.local_plan_viapoint_sep = 0.5;
//#line 85 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      trajectory.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("local_plan_viapoint_sep", "double", 0, "Min. separation between each two consecutive via-points extracted from the global plan [if negative: disabled]", "", &GeoLocalPlannerReconfigureConfig::local_plan_viapoint_sep)));
//#line 85 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("local_plan_viapoint_sep", "double", 0, "Min. separation between each two consecutive via-points extracted from the global plan [if negative: disabled]", "", &GeoLocalPlannerReconfigureConfig::local_plan_viapoint_sep)));
//#line 89 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.local_plan_goal_sep = -0.1;
//#line 89 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.local_plan_goal_sep = 10.0;
//#line 89 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.local_plan_goal_sep = 0.5;
//#line 89 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      trajectory.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("local_plan_goal_sep", "double", 0, "Min. separation between last via-points extracted from the global plan and goal", "", &GeoLocalPlannerReconfigureConfig::local_plan_goal_sep)));
//#line 89 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("local_plan_goal_sep", "double", 0, "Min. separation between last via-points extracted from the global plan and goal", "", &GeoLocalPlannerReconfigureConfig::local_plan_goal_sep)));
//#line 93 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.local_plan_prune_distance = -0.1;
//#line 93 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.local_plan_prune_distance = 10.0;
//#line 93 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.local_plan_prune_distance = 1.0;
//#line 93 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      trajectory.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("local_plan_prune_distance", "double", 0, "Distance between robot and via_points of global plan which is used for pruning", "", &GeoLocalPlannerReconfigureConfig::local_plan_prune_distance)));
//#line 93 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("local_plan_prune_distance", "double", 0, "Distance between robot and via_points of global plan which is used for pruning", "", &GeoLocalPlannerReconfigureConfig::local_plan_prune_distance)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      trajectory.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(GeoLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT::TRAJECTORY, GeoLocalPlannerReconfigureConfig::DEFAULT>(trajectory)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT::TRAJECTORY, GeoLocalPlannerReconfigureConfig::DEFAULT>(trajectory)));
GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT::OPTIMIZATION, GeoLocalPlannerReconfigureConfig::DEFAULT> Optimization("Optimization", "tab", 0, 5, true, &GeoLocalPlannerReconfigureConfig::DEFAULT::optimization);
//#line 100 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.k_rho = 0.0;
//#line 100 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.k_rho = 10.0;
//#line 100 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.k_rho = 1.0;
//#line 100 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      Optimization.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("k_rho", "double", 0, "Proportional parameter for linear velocity adjustment based on the Euclidean distance of the robot position to the current target", "", &GeoLocalPlannerReconfigureConfig::k_rho)));
//#line 100 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("k_rho", "double", 0, "Proportional parameter for linear velocity adjustment based on the Euclidean distance of the robot position to the current target", "", &GeoLocalPlannerReconfigureConfig::k_rho)));
//#line 104 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.k_alpha = -10.0;
//#line 104 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.k_alpha = 10.0;
//#line 104 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.k_alpha = -3.0;
//#line 104 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      Optimization.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("k_alpha", "double", 0, "Proportional parameter for angular velocity adjustment based on the tangential angle of the target position in the robot's frame of reference", "", &GeoLocalPlannerReconfigureConfig::k_alpha)));
//#line 104 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("k_alpha", "double", 0, "Proportional parameter for angular velocity adjustment based on the tangential angle of the target position in the robot's frame of reference", "", &GeoLocalPlannerReconfigureConfig::k_alpha)));
//#line 108 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __min__.k_phi = -10.0;
//#line 108 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __max__.k_phi = 10.0;
//#line 108 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __default__.k_phi = -1.0;
//#line 108 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      Optimization.abstract_parameters.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("k_phi", "double", 0, "Proportional parameter for angular velocity adjustment based on the difference between the robot's orientation(yaw) and the current target orientation(yaw)", "", &GeoLocalPlannerReconfigureConfig::k_phi)));
//#line 108 "/home/hao/ros_ws/src/geo_local_planner/cfg/GeoLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::ParamDescription<double>("k_phi", "double", 0, "Proportional parameter for angular velocity adjustment based on the difference between the robot's orientation(yaw) and the current target orientation(yaw)", "", &GeoLocalPlannerReconfigureConfig::k_phi)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Optimization.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(GeoLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT::OPTIMIZATION, GeoLocalPlannerReconfigureConfig::DEFAULT>(Optimization)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT::OPTIMIZATION, GeoLocalPlannerReconfigureConfig::DEFAULT>(Optimization)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(GeoLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new GeoLocalPlannerReconfigureConfig::GroupDescription<GeoLocalPlannerReconfigureConfig::DEFAULT, GeoLocalPlannerReconfigureConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<GeoLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<GeoLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    GeoLocalPlannerReconfigureConfig __max__;
    GeoLocalPlannerReconfigureConfig __min__;
    GeoLocalPlannerReconfigureConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const GeoLocalPlannerReconfigureConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static GeoLocalPlannerReconfigureConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &GeoLocalPlannerReconfigureConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const GeoLocalPlannerReconfigureConfig &GeoLocalPlannerReconfigureConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const GeoLocalPlannerReconfigureConfig &GeoLocalPlannerReconfigureConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const GeoLocalPlannerReconfigureConfig &GeoLocalPlannerReconfigureConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<GeoLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr> &GeoLocalPlannerReconfigureConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<GeoLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr> &GeoLocalPlannerReconfigureConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const GeoLocalPlannerReconfigureConfigStatics *GeoLocalPlannerReconfigureConfig::__get_statics__()
  {
    const static GeoLocalPlannerReconfigureConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = GeoLocalPlannerReconfigureConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __GEOLOCALPLANNERRECONFIGURERECONFIGURATOR_H__
